@startuml
' ユースケース図の練習
' 【重要】あまり詳細にかかなくていい！！！

' 図のタイトルはtitleで指定
title ユースケース図

' アクター（登場人物）はactorで指定
' アクターちゃんと担当役割名を明確に
actor 書籍管理者
actor お客様

' 図を描く方向性を変更
left to right direction

' アクターとかを一人にしたい場合は下記
hide footbox

'システムの境界線
rectangle 書籍管理システム{

	' ユースケースはusecaseで指定
	usecase 書籍検索機能
	usecase 書籍一覧機能
	usecase 書籍登録機能
	usecase 書籍削除機能
	usecase 書籍貸出機能

}
' 変数名を-->で関連付けられる
書籍管理者 --> 書籍一覧機能
書籍管理者 --> 書籍登録機能
書籍管理者 --> 書籍削除機能
書籍管理者 --> 書籍貸出機能
書籍管理者 --> 書籍検索機能
お客様 <-- 書籍検索機能

@enduml